on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          date > generated.txt
          date > discard.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add generated.txt
          git commit -m "generated"
          git checkout push-to
          git push origin push-to
